### ISSUE TITLE
Support inheritance for @Input properties

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/angular2#291] opened 2017-03-05 19:54 UTC
This is not new, but I didn't find it in open issues here and I guess it should be documented:

     class BaseComponent {

       @Input()
       String name;

     }

     @Component(
       selector: 'child-component',
       template: '''
         <h1>Hello {{name}}!</h1>
         '''
     )
     class ChildComponent extends BaseComponent {
     
     }

Calling this component like this:

    <child-component name="Angular"></child-component>

... renders "Hello !" instead of expected "Hello Angular!".

Real world example: I have a bunch of custom "input" components of all kind and they all can be "required", "readonly", "disabled", ... It make sense to define these properties in shared parent or in a mixin ...

Just another case for https://github.com/dart-lang/angular2/issues/48 :-)

**Comment by chalin** [comment] 2017-03-15 22:06
Generally speaking, I'm not sure that the semantics of inheritance for component metadata properties has been fully nailed down.

Anyhow, a **workaround** to the issue you mention is, of course, to provide a complete list of supported inputs and or output in the annotation of `ChildComponent`:
```dart
@Component(...,
    inputs: const ['name'], // <***************************
    template: '<h1>Hello {{name}}</h1>'
)
class ChildComponent extends BaseComponent { }
```

cc @kwalrath

**Comment by matanlurey** [comment] 2017-03-16 01:31
This is really important to me, but yes, we need to figure out semantics. It will be post-V3.

**Comment by matanlurey** [comment] 2017-05-12 00:51
Duplicate of https://github.com/dart-lang/angular2/issues/231.

**Closed by matanlurey** 2017-05-12 00:51 UTC
Labels: P2 medium, State: blocked, Type: enhancement
