### ISSUE TITLE
passing closure to polymer.dart element fails in beta19, worked in previous versions

### ISSUE THREAD

**Issue by hentoesch** [dart-lang/angular2#32] opened 2016-08-02 10:00 UTC
i am using polymer.dart and angular 2 together in a project.

i have a polymer element to which i pass a closure from my angular2 element like so:

<data-list 
  ...
  [contextMenuItems]="addressBookData.getContextMenuItems"
  ...

this used to work up until beta18.

in beta19 i am getting the following exception:

ORIGINAL EXCEPTION: 
Invalid argument(s): Attempt to pass Function 'Closure: (dynamic) => List<ContextMenuItem> from Function 'getContextMenuItems':.' to JavaScript via without calling allowInterop or allowInteropCaptureThis
ORIGINAL STACKTRACE:

```
#0      safeForTypedInterop (dart:js:1471)
#1      ngSetProperty (package:angular2/src/platform/browser/browser_adapter.dart_js_interop_patch.dart:31:3)
#2      BrowserDomAdapter.setProperty (package:angular2/src/platform/browser/browser_adapter.dart:180:7)
#3      DomRenderer.setElementProperty (package:angular2/src/platform/dom/dom_renderer.dart:194:9)
#4      _View_NgAddressBookList0.detectChangesInternal (package:direkt_web/views/client/address/ngaddressbook_list.template.dart:322:21)
#5      AppView.detectChanges (package:angular2/src/core/linker/view.dart:245:10)
#6      DebugAppView.detectChanges (package:angular2/src/core/linker/view.dart:366:26)
#7      AppView.detectViewChildrenChanges (package:angular2/src/core/linker/view.dart:269:23)
#8      _View_NgAddressBookList_Host0.detectChangesInternal (package:direkt_web/views/client/address/ngaddressbook_list.template.dart:441:10)
#9      AppView.detectChanges (package:angular2/src/core/linker/view.dart:245:10)
#10     DebugAppView.detectChanges (package:angular2/src/core/linker/view.dart:366:26)
#11     AppView.detectContentChildrenChanges (package:angular2/src/core/linker/view.dart:262:31)
#12     _View_MainApp0.detectChangesInternal (package:direkt_web/main_app.template.dart:335:10)
#13     AppView.detectChanges (package:angular2/src/core/linker/view.dart:245:10)
#14     DebugAppView.detectChanges (package:angular2/src/core/linker/view.dart:366:26)
#15     AppView.detectViewChildrenChanges (package:angular2/src/core/linker/view.dart:269:23)
#16     _View_MainApp_Host0.detectChangesInternal (package:direkt_web/main_app.template.dart:1087:10)
#17     AppView.detectChanges (package:angular2/src/core/linker/view.dart:245:10)
#18     DebugAppView.detectChanges (package:angular2/src/core/linker/view.dart:366:26)
#19     ViewRef_.detectChanges (package:angular2/src/core/linker/view_ref.dart:99:11)
#20     ApplicationRef_.tick.<anonymous closure> (package:angular2/src/core/application_ref.dart:443:63)
#21     List.forEach (dart:core-patch/growable_array.dart:254)
#22     ApplicationRef_.tick (package:angular2/src/core/application_ref.dart:443:32)
#23     ApplicationRef_.ApplicationRef_.<anonymous closure>.<anonymous closure> (package:angular2/src/core/application_ref.dart:326:14)
#24     _rootRun (dart:async/zone.dart:895)
#25     _ZoneDelegate.run (dart:async/zone.dart:490)
#26     NgZoneImpl._run (package:angular2/src/core/zone/ng_zone_impl.dart:155:21)
#27     _CustomZone.run (dart:async/zone.dart:790)
#28     NgZoneImpl.runInner (package:angular2/src/core/zone/ng_zone_impl.dart:126:23)
#29     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:220:27)
#30     ApplicationRef_.ApplicationRef_.<anonymous closure> (package:angular2/src/core/application_ref.dart:325:18)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1075)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#34     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:381)
#35     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:256)
#36     EventEmitter.emit (package:angular2/src/facade/async.dart:94:17)
#37     NgZone._checkStable (package:angular2/src/core/zone/ng_zone.dart:145:34)
#38     NgZone.NgZone.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:128:16)
#39     NgZoneImpl._run (package:angular2/src/core/zone/ng_zone_impl.dart:157:14)
#40     _CustomZone.run (dart:async/zone.dart:790)
#41     _CustomZone.runGuarded (dart:async/zone.dart:696)
#42     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#45     _ScheduleImmediateHelper._handleMutation (dart:html:49290)
```

**Comment by zoechi** [comment] 2016-08-02 10:03
Have you tried wrapping it with `allowInterop(...)`? (import from `package:js`)

I assume you need to do this in Dart code (not in the template).
This seems to be caused by the change from `dart:js` to `package:js`

**Comment by hentoesch** [comment] 2016-08-02 10:10
i tried the following:

in dart code:
get getContextMenuItems => allowInterop(addressBookData.getContextMenuItems);

in html:
<data-list 
...
[contextMenuItems]="getContextMenuItems"
...

which does not provoke the original exception.
but when i call the closure in my polymer element i get the following exception:

Class 'JsFunction' has no instance method 'call'.

NoSuchMethodError: method not found: 'call'
Receiver: Instance of 'JsFunction'
Arguments: [_LinkedHashMap len:20]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      DataList._showMenu (package:direkt_web/widgets/polymer/data_list.dart:300:54)
#3      DataList.selectionHandler (package:direkt_web/widgets/polymer/data_list.dart:281:9)
#4      Function._apply (dart:core-patch/function_patch.dart:7)
#5      Function.apply (dart:core-patch/function_patch.dart:28)
#6      _InstanceMirrorImpl.invoke (package:reflectable/src/reflectable_transformer_based.dart:259:21)
#7      addDeclarationToPrototype.<anonymous closure> (package:polymer/src/common/declarations.dart:134:35)

**Comment by matanlurey** [comment] 2016-08-02 14:37
Does this happen in dart2js, Dartium, or both?

**Comment by hentoesch** [comment] 2016-08-02 15:35
this one only happens in dartium.

**Comment by matanlurey** [comment] 2016-08-02 16:07
@jacob314 I think I saw this problem also when I was working on https://github.com/matanlurey/js-interop-examples (https://github.com/matanlurey/js-interop-examples/blob/master/web/vscode_example.dart#L10). Any insight?

**Comment by zoechi** [comment] 2016-08-21 14:36
@hentoesch can you please fix the code formatting in your comments (wrap code in triple backticks) 
Currently all line numbers are treated as references to other issues that also show up as back-reference to this issue there.

**Comment by hentoesch** [comment] 2016-09-09 16:16
finally found some time  to track down the problem, which still persists in beta 21.
it is working now in dartium, but in chrome after darts2js it still does not work.

dart 1.19, ubuntu 16.04, chrome 53

i have the following constellation:

1) from angular i pass a dart object "model" to my polymer element

class Model {
  @reflectable
  Function callback;
  @reflectable
  String param;

}


2) in my polymer html markup i call a function the gets this aobject as a parameter
<div>{{callModel(model)}}</div>

which looks like:

callModel(model) {
  model.callback(model.param); 
}

3) after angular 21 the callModel() function  gets called, but the parameter "model"  in chrome is a JsObject - which does not know anything about a callback.

i built a litlle project reproduce this bug:

https://github.com/hentoesch/angular_hates_polymer

any ideas?

**Comment by matanlurey** [comment] 2016-09-15 08:02
@jacob314 Are we missing something trivial?

**Comment by matanlurey** [comment] 2016-11-29 03:45
Closing since we haven't gotten any feedback since September.

**Closed by matanlurey** 2016-11-29 03:45 UTC
Labels: P1 high, Type: bug
