### ISSUE TITLE
OnDeactivate not called on browser tab closing.

### ISSUE THREAD

**Issue by giorgiofran** [dart-lang/angular2#45] opened 2016-08-16 10:35 UTC
I'm using routing and everything seems to work fine.
I have a function that store same data on an external Db when a certain component is deactivated.
This works good when I'm moving to another route, but, If I close the browser, it is not called.
Now I don't know if this is by design or if it should be considered a bug.
If not a bug, may you please give an hint on how to avoid this problem?

**Comment by wem** [comment] 2016-08-16 11:33
You can register a listener on the window itself window.onUnload.listen((Event event ) {}), for example in the ngOnInit callback. Afaik this is not a bug.

**Comment by giorgiofran** [comment] 2016-08-16 13:16
Thanks, in my case the listener should work.
Anyway, I believe that it would be a better design to have a call to onDeactivate for any corresponding onActivate

**Comment by matanlurey** [comment] 2016-08-19 01:51
So, we are currently in the process of doing a major overhaul on the router, so it's unlikely we'll get this addressed - the existing router is a straight port from the older TS version and has significant issues. I am tagging this so we can make sure it's addressed in the new design.

**Closed by matanlurey** 2016-08-19 01:51 UTC
Labels: Resolution: wontfix, Type: bug
