### ISSUE TITLE
Is there a roadmap for Angular2 Dart

### ISSUE THREAD

**Issue by jrote1** [dart-lang/angular2#44] opened 2016-08-10 14:17 UTC

**Comment by kulshekhar** [comment] 2016-08-13 16:24
This would be very helpful if it could address questions like:

- Will there be an attempt to maintain feature parity with Angular2 TS?
- Will the design decisions be affected by those in Angular2 TS?
- Will recent changes (like the introduction of `ngModule`) in Angular2 TS be forced upon Angular2 Dart just because they are present in the TS version?

If we can have some clarity on the direction Angular2 Dart is going in and on the constraints that will drive design decisions, it will be immensely helpful. 

For example, I have to choose which framework to use next (I've used AngularJS for about 3 years but it is no longer an option) and once I make this choice, I'll be using it for at least the next 2-3 years over several projects.

- I want to use Angular2 Dart (mainly because the dev workflow is straightforward)
- I will NOT use Angular2 TS unless I'm forced to
- I won't choose Angular2 Dart until there's some clarity and predictability on how it is going to develop
- I can't wait for too long before I have to make a decision

I'm sure there are a lot of other people (at least outside Google) who would appreciate some concrete information on this, something more than

> The framework will feel more like idiomatic Dart.
> It will make use of Dart features that couldn't work with the TypeScript flavor.
> It will be faster

as was posted in [this post](http://news.dartlang.org/2016/07/angulardart-is-going-all-dart.html)

**Comment by matanlurey** [comment] 2016-08-16 22:13
Got it, we'll get something (rough) out soon. This is *not* being ignored, we just want to make sure we have consistent messaging. One thing quick - we have *no* mandate to copy or follow the Angular 2 TS project - in fact for example `NgModule` is something we've identified that we can do better for our Dart users without forcing large migrations. 

I'll be uploading a `ROADMAP.md` in a PR with more information.

**Comment by kriry** [comment] 2016-08-17 12:11
great!

**Comment by matanlurey** [comment] 2016-08-18 19:04
Closed in the most recent sync. Let us know if you have any general questions.

**Closed by matanlurey** 2016-08-18 19:04 UTC
Labels: Type: question

**Comment by cporte** [comment] 2016-08-19 07:09
Thanks for the roadmap!
Not a question, more like a wish: Angular 2 TS RC cycles were really strange (lots of deprecation, router n°2 then n°3 in a few RCs, etc, without proper communication) and I'm not really aware of all the details (and we are probably many who just stopped looking at all the changes when the Dart version went missing).
We now know the router and forms will probably change, certainly a lot to be aligned with Angular 2 TS.
When the time comes for those changes, it would be great to keep the communication as good as you guys are doing (warn about when the changes will come, give a couple of links to resources about what we will have to adapt, etc, so we can plan ahead the impact on our side)

**Comment by zoechi** [comment] 2016-08-19 12:39
> Angular 2 TS RC cycles were really strange

If your crystal ball provides better results about the future please borrow it to the Angular2 team ;-)

These "strangeness" wasn't planned or out of sloppyness, but was caused by unexpected issues that turned up while they worked towards release. 

Nothing against good communication myself though.  
We should just be aware that good communication takes a lot of time that can't be used to fix issues or implement cool features.
