### ISSUE TITLE
Angular Dart transformer silently ignores `entry_points` files that do not exist

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular2#38] opened 2016-08-05 16:52 UTC
Consider the following excerpt from a `pubspec.yaml`:
```yaml
...
transformers:
- angular2:
    platform_directives: ...
    platform_pipes: ...
    entry_points: SOME/FILE_DOES_NOT_EXIST.dart
```

**Current behavior**
Running `pub serve` reports no error (but then fails to identify target types for static code generation), and so the app usually fails later down the road.

**Expected/desired behavior**
It would be nice if the transformer would at least report an error or warning if the `entry_points` do not exist.

* **Angular version:** 2.0.0-beta.17
* **Browser:** Chrome 50 | Chromium 45 
* **Language:** Dart

Migrated from https://github.com/angular/angular/issues/8897.

**Comment by chalin** [comment] 2016-08-05 16:57
cc @kwalrath

**Comment by matanlurey** [comment] 2016-09-07 17:39
Closed by https://github.com/dart-lang/angular2/issues/38.

**Closed by matanlurey** 2016-09-07 17:39 UTC
Labels: P3 low, State: help wanted, Type: bug

**Comment by chalin** [comment] 2016-09-07 23:41
Fixed by #51. Thanks @zoechi!

**Comment by AndreyChernykh** [comment] 2016-09-08 09:52
@chalin In case we have situation described below, we got an error "The value ".....dart" in "entry_points" of the Angular 2 transformer configuration does not point to any file.": 

Considering we have 2 projects, both are Angular apps. If we include the first one into the second one just to use it's components as a part of the bigger application, Angular ignores this fact and still tries to process the entry point of subordinate package. 

// We need to keep a Feature app as a separate Ng app to be able to develop and debug it faster. 
`// pubspec.yaml Feature app
name: my_feature
dependencies:
  angular2: 2.0.0-beta.21
transformers:
  - angular2:
    entry_points: web/feature_main.dart
`

// But we use a Feature app as a part of a bigger app
`// pubspec.yaml Feature app
name: my_app
dependencies:
  angular2: 2.0.0-beta.21
  my_feature: any
transformers:
  - angular2:
    entry_points: web/main.dart
`

**Comment by matanlurey** [comment] 2016-09-08 14:39
I'm not intimately familiar with pub transformers. Did this work before 21?

**Comment by AndreyChernykh** [comment] 2016-09-08 15:13
Yes. I was OK even with 20. 

I am going to check it more precisely, but it really seems that this behavior was caused by this fix.

**Comment by matanlurey** [comment] 2016-09-08 15:18
@zoechi: Could we relax the requirements in the `entry_points` linter or allow an opt-out?

**Comment by zoechi** [comment] 2016-09-08 15:45
@matanlurey @AndreyChernykh it seems to be the same issue as I reported in #64
