### ISSUE TITLE
b21: library import issues after the angular 2 transformer runs

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/angular2#67] opened 2016-09-07 09:59 UTC
I have a library where a class called Document resides

When I create a component that uses this Document class, I just import the library that provides it, without an alias, e.g. import 'package:library_containing_document_class.dart';

In this component, I did not import 'dart:html'.

The transformer however does import dart:html when it runs, and I get an exception saying:

'Document' from library 'dart:html' is hidden by 'Document' from library 'package:library_containing_document_class.dart'.
'Document' is imported here.
Try adding 'hide Document' to the import of 'dart:html'.

The transformer should introduce new imports always with a generated alias to avoid these conflicts

**Comment by matanlurey** [comment] 2016-09-07 17:42
I agree with prefixing in this case. Triaging.

**Comment by matanlurey** [comment] 2016-09-15 08:07
Duplicate of https://github.com/dart-lang/angular2/issues/77

**Closed by matanlurey** 2016-09-15 08:07 UTC
Labels: P2 medium, Type: bug

**Comment by matanlurey** [comment] 2016-09-15 16:49
@frankpepermans This is WAI.

We require our users to properly prefix themselves or avoid colliding with dart:html.

**Comment by frankpepermans** [comment] 2016-09-15 17:03
Can you elaborate on why this won't be fixed? Just curious, this kind of means you need to prefix everything you import, because something could always collide name wise, if not today, then maybe after an sdk update when a new class gets introduced to dart:html, or whatever other library the transformer could include.

**Comment by matanlurey** [comment] 2016-09-15 17:05
We are a web based framework, so it's expected this will be ~ 1:1 with dart:html. We don't expect to add any other libraries without prefixng, but dart:html. Similar to if you try to use `Document` in any JS app ;P

**Comment by frankpepermans** [comment] 2016-09-15 19:31
I disagree about being tied 1 to 1 with the web, theoretically, I could extend or mixin controller code, which is platform agnostic. Say I target both web and mobile and want to share code? (Flutter comes to mind). Or perhaps server side rendering should it ever be implemented? 

It seems like a clean and easy solution to have the transformer take care of prefixing, or is there a technical issue preventing this?

**Comment by matanlurey** [comment] 2016-09-15 20:31
I understand. This might be possible in the future, but it's not on the roadmap for now.

Right now every generated `AppView` is expected to import `dart:html` as that is our only target.
