### ISSUE TITLE
How to build as form with angular components

### ISSUE THREAD

**Issue by kostonstyle** [dart-lang/angular2#198] opened 2016-11-16 07:17 UTC
I want to build an authentication form with angular component and tried as follow:

```
<form (ngSubmit)="onSubmit()" #loginCtrl="ngForm">
    <div class="input">
         <material-input type="text"
                        class="login"
                        required
                        floatingLabel
                        label="User"
                        [(ngModel)]="login.user"
                        ngControl="user"
                        #user="ngForm"></material-input>
    </div>
    <div class="input">
        <material-input
                class="login"
                type="password"
                floatingLabel label="Password"
                [(ngModel)]="login.password">
        </material-input>
    </div>
    <div class="input">
        <material-input
                class="login"
                type="text"
                floatingLabel
                label="Language"
                [(ngModel)]="login.language">
        </material-input>
    </div>
    <div class="input">
        <material-button
                type="submit"
                raised
                class="btn-blue">
            Login
        </material-button>
    </div>
</form>

```
the function onSubmit does not get triggered at all. What am I doing wrong?

Thanks

**Comment by lejard-h** [comment] 2016-11-16 19:14
Replace `(ngSubmit)="onSubmit()"` by `(submit)="onSubmit()`.

It should work ;)

**Comment by matanlurey** [comment] 2016-11-19 20:26
Check out this example:

https://github.com/dart-lang/angular2/blob/e7d4c521db77cb9b98ec36f1afbbd66b521586d7/lib/src/common/forms/directives/ng_form.dart#L51

**Comment by matanlurey** [comment] 2017-04-04 20:13
@kevmoo @kwalrath Do we have docs now on forms usage? Can we close this?

**Comment by kwalrath** [comment] 2017-04-04 20:20
I don't know about this particular usage, but we've had a [forms page](https://webdev.dartlang.org/angular/guide/forms) for quite a while. @chalin might have more thoughts.

**Comment by chalin** [comment] 2017-04-06 16:09
@kostonstyle - if you use regular HTML elements for `<input>`, `<button>` etc, do you have the same issue?  See the [forms page](https://webdev.dartlang.org/angular/guide/forms) for more information; it was fully reviewed a few months ago and should be up-to-date concerning plain angular forms.

If your app works for plain angular form elements, then maybe the issue is with angular components? Much has changed since this issue was open. It may be worth trying your app over angular 3.0.0-beta and the latest angular components.

Either way, @matanlurey I suggest closing this PR.

If there still is an problem, then an issue should either be open over angular components or [dart-lang/site-webdev](https://github.com/dart-lang/site-webdev/issues) requesting an example of forms using angular components.

**Closed** 2017-05-12 00:36 UTC
Labels: Type: question
